include: package:surf_lint_rules/analysis_options.yaml

name: places
description: my flutter project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dart_code_metrics: ^4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Light.ttf
        - asset: res/fonts/Roboto-Thin.ttf
        - asset: res/fonts/Roboto-Italic.ttf

analyzer:
  exclude:
    - "build/**"
    - "script/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
    number-of-methods: 10
    weight-of-class: 0.33
    maintainability-index: 50
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics-exclude:
    - test/**
  rules:
    - always-remove-listener
    - avoid-unused-parameters
    - avoid-unnecessary-setstate
    - double-literal-format
    - newline-before-return
    - no-boolean-literal-compare
    - prefer-conditional-expressions
    - prefer-intl-name
    - provide-correct-intl-args

linter:
  rules:
    public_member_api_docs: false
    always_put_required_named_parameters_first: false
    always_use_package_imports: true
