name: places
description: my flutter project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dart_code_metrics: ^4.16.0
  flutter:
    sdk: flutter
  surf_lint_rules: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/assets/
  fonts:
    - family: Roboto
      fonts:
        - asset: res/assets/fonts/Roboto/Roboto-Light.ttf
        - asset: res/assets/fonts/Roboto/Roboto-Thin.ttf
        - asset: res/assets/fonts/Roboto/Roboto-Italic.ttf
